-- 1) TABLES
CREATE TABLE products (
  product_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  sku           VARCHAR2(50) UNIQUE,
  name          VARCHAR2(200) NOT NULL,
  description   VARCHAR2(1000),
  price         NUMBER(10,2) NOT NULL,
  stock_qty     NUMBER NOT NULL,
  created_at    DATE DEFAULT SYSDATE
);

CREATE TABLE customers (
  customer_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR2(100) NOT NULL,
  last_name     VARCHAR2(100) NOT NULL,
  email         VARCHAR2(200) UNIQUE NOT NULL,
  phone         VARCHAR2(50),
  customer_type VARCHAR2(20) DEFAULT 'REGULAR', -- e.g. REGULAR, VIP
  created_at    DATE DEFAULT SYSDATE
);

CREATE TABLE orders (
  order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  customer_id   NUMBER NOT NULL,
  order_date    DATE DEFAULT SYSDATE,
  status        VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, CONFIRMED, SHIPPED, CANCELLED
  subtotal      NUMBER(12,2) DEFAULT 0,
  discount_amt  NUMBER(12,2) DEFAULT 0,
  tax_amt       NUMBER(12,2) DEFAULT 0,
  total_amt     NUMBER(12,2) DEFAULT 0,
  CONSTRAINT fk_ord_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id      NUMBER NOT NULL,
  product_id    NUMBER NOT NULL,
  quantity      NUMBER NOT NULL,
  unit_price    NUMBER(10,2) NOT NULL,
  line_total    NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
  CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE payments (
  payment_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id      NUMBER NOT NULL,
  paid_amount   NUMBER(12,2) NOT NULL,
  paid_date     DATE DEFAULT SYSDATE,
  payment_method VARCHAR2(50),
  CONSTRAINT fk_pay_order FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- 2) SAMPLE DATA
INSERT INTO products (sku, name, description, price, stock_qty) VALUES ('SKU-001','Wireless Mouse','Ergonomic wireless mouse', 19.99, 150);
INSERT INTO products (sku, name, description, price, stock_qty) VALUES ('SKU-002','Mechanical Keyboard','RGB mechanical keyboard', 79.99, 80);
INSERT INTO products (sku, name, description, price, stock_qty) VALUES ('SKU-003','USB-C Cable','1.5m USB-C cable', 9.99, 300);
INSERT INTO products (sku, name, description, price, stock_qty) VALUES ('SKU-004','Laptop Stand','Aluminum laptop stand', 39.99, 40);
INSERT INTO products (sku, name, description, price, stock_qty) VALUES ('SKU-005','Webcam 1080p','Full HD webcam', 49.99, 60);

INSERT INTO customers (first_name, last_name, email, phone, customer_type) VALUES ('Asha','Patel','asha.patel@example.com','+91-9876543210','REGULAR');
INSERT INTO customers (first_name, last_name, email, phone, customer_type) VALUES ('Rahul','Mehra','rahul.mehra@example.com','+91-9123456780','VIP');
INSERT INTO customers (first_name, last_name, email, phone, customer_type) VALUES ('Maya','Kumar','maya.kumar@example.com','+91-9988776655','REGULAR');